### ISSUE TITLE
seismic rectangular sources error in check_rect_source_discretisation

### ISSUE THREAD

**Issue by braunfuss** [pyrocko/pyrocko#321] opened 2018-11-01 14:11 UTC
Seismic rectangular sources will return a `check_rect_source_discretisation`. This can be reproduced on several computer. 
Using the Seismosizer snuffling and `global_2s` store for example will reproduce this error. 
```
Traceback (most recent call last): File "/usr/local/bin/grond", line 11, in <module> load_entry_point('grond==0.2', 'console_scripts', 'grond')() File "/usr/local/lib/python3.5/dist-packages/grond/apps/grond.py", line 158, in main globals()'command_' + d2u(command) File "/usr/local/lib/python3.5/dist-packages/grond/apps/grond.py", line 531, in command_go nparallel=options.nparallel) File "/usr/local/lib/python3.5/dist-packages/grond/core.py", line 458, in go nprocs=nparallel): File "/usr/local/lib/python3.5/dist-packages/pyrocko/parimap.py", line 59, in parimap yield function(args, *kwargs)
  File "/usr/local/lib/python3.5/dist-packages/grond/core.py", line 510, in process_event
    analyser.analyse(problem, ds)
  File "/usr/local/lib/python3.5/dist-packages/grond/analysers/target_balancing/analyser.py", line 94, in analyse
    ms = wproblem.misfits(x, mask=isok_mask)[:, 1]
  File "/usr/local/lib/python3.5/dist-packages/grond/problems/base.py", line 586, in misfits
    results = self.evaluate(x, mask=mask, result_mode='sparse')
  File "/usr/local/lib/python3.5/dist-packages/grond/problems/base.py", line 554, in evaluate
    resp = engine.process(sources, modelling_targets_unique)
  File "/usr/local/lib/python3.5/dist-packages/pyrocko/gf/seismosizer.py", line 3149, in process
    nthreads=nthreads):
  File "/usr/local/lib/python3.5/dist-packages/pyrocko/gf/seismosizer.py", line 2695, in process_dynamic
    source, target, components, dsource_cache, nthreads)
  File "/usr/local/lib/python3.5/dist-packages/pyrocko/gf/seismosizer.py", line 2977, in base_seismogram
    source, store_, dsource_cache, target)
  File "/usr/local/lib/python3.5/dist-packages/pyrocko/gf/seismosizer.py", line 2955, in _cached_discretize_basesource
    cache[source, store] = source.discretize_basesource(store, target)
  File "/usr/local/lib/python3.5/dist-packages/grond/problems/base.py", line 83, in discretize_basesource
    ds = sf.discretize_basesource(store, target)
  File "/usr/local/lib/python3.5/dist-packages/pyrocko/gf/seismosizer.py", line 1815, in discretize_basesource
    points, times, amplitudes, dl, dw = self._discretize(store, target)
  File "/usr/local/lib/python3.5/dist-packages/pyrocko/gf/seismosizer.py", line 1788, in _discretize
    if not check_rect_source_discretisation(points, nl, nw, store):
  File "/usr/local/lib/python3.5/dist-packages/pyrocko/gf/seismosizer.py", line 235, in check_rect_source_discretisation
    (points[1, 0,  - points[1, 1, :])2 +
```

**Comment by miili** [comment] 2018-11-01 14:29
Can you post the full traceback?

**Comment by hvasbath** [comment] 2018-11-01 14:49
Duplicate of https://github.com/pyrocko/pyrocko/issues/308

**Comment by miili** [comment] 2018-11-01 16:04
fixed in https://github.com/pyrocko/pyrocko/pull/322/commits/5166848f056723e6555c7afaeace75dfa73dc749

**Comment by braunfuss** [comment] 2018-11-02 13:33
also rectangular sources for statics now produce an error:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/grond/monitor.py", line 61, in run
    self.history = self.environment.get_history()
AttributeError: 'NoneType' object has no attribute 'get_history'

Traceback (most recent call last):
  File "/usr/local/bin/grond", line 11, in <module>
    load_entry_point('grond==0.2', 'console_scripts', 'grond')()
  File "/usr/local/lib/python3.5/dist-packages/grond/apps/grond.py", line 158, in main
    globals()['command_' + d2u(command)](args)
  File "/usr/local/lib/python3.5/dist-packages/grond/apps/grond.py", line 531, in command_go
    nparallel=options.nparallel)
  File "/usr/local/lib/python3.5/dist-packages/grond/core.py", line 458, in go
    nprocs=nparallel):
  File "/usr/local/lib/python3.5/dist-packages/pyrocko/parimap.py", line 59, in parimap
    yield function(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/grond/core.py", line 542, in process_event
    rundir=rundir)
  File "/usr/local/lib/python3.5/dist-packages/grond/optimisers/highscore/optimiser.py", line 502, in optimise
    misfits = problem.misfits(x, mask=isok_mask)
  File "/usr/local/lib/python3.5/dist-packages/grond/problems/base.py", line 586, in misfits
    results = self.evaluate(x, mask=mask, result_mode='sparse')
  File "/usr/local/lib/python3.5/dist-packages/grond/problems/base.py", line 554, in evaluate
    resp = engine.process(sources, modelling_targets_unique)
  File "/usr/local/lib/python3.5/dist-packages/pyrocko/gf/seismosizer.py", line 3176, in process
    nthreads=nthreads):
  File "/usr/local/lib/python3.5/dist-packages/pyrocko/gf/seismosizer.py", line 2747, in process_static
    source, target, components, nthreads)
  File "/usr/local/lib/python3.5/dist-packages/pyrocko/gf/seismosizer.py", line 3029, in base_statics
    nthreads)
  File "/usr/local/lib/python3.5/dist-packages/pyrocko/gf/store.py", line 1848, in statics
    nthreads)
pyrocko.gf.store_ext.StoreExtError: w_store_calc_static: unhealthy delays array

**Comment by miili** [comment] 2018-11-06 11:05
Resolved with https://github.com/pyrocko/pyrocko/pull/322

**Closed by miili** 2018-11-06 11:05 UTC
