### ISSUE TITLE
Installation problems [snuffler]

### ISSUE THREAD

**Issue by neatcoder** [pyrocko/pyrocko#244] opened 2017-12-18 11:11 UTC
Hello!

I tried to install pyrocko manually and through Anaconda for both Python 2 and Python 3 versions. I found out that, when running snuffler, only manual installation for Python 2 works without problems. For other installations various errors occur.

Manual installation for Python 3 when running snuffler gives:
Segmentation fault (core dumped).

Install within Anaconda for Python 2 when running snuffler gives (separate environment):
pkg_resources.DistributionNotFound: The 'pyrocko==2017.11.22' distribution was not found and is required by the application
Anaconda shows that this distribution is correctly installed.

Install within Anaconda for Python3 when running snuffler gives (separate environment):
ImportError: /home/gregor/anaconda2/envs/pyrocko3/bin/../lib/libQt5Core.so.5: version `Qt_5.8' not found (required by /home/gregor/anaconda2/envs/pyrocko3/lib/python3.6/site-packages/PyQt5/QtCore.so)
Latest version of pyqt available is 5.6.2.

Before I run snuffler, installed with pyrocko inside Anaconda, I always activate appropriate environment.

I am running Ubuntu 16.04. All manual installations are done using elevated access (sudo command).

Thanks for your consideration.

**Comment by emolch** [comment] 2017-12-18 13:58
Hi,
Anaconda installations sometimes suffer from incompatibilities within the various PyQt / Qt versions. The reasons can be manifold.

I am not using Anaconda usually, so I don't know all the details. I just downloaded a fresh copy of Anaconda3, installed it in my home directory and used 'conda install -c pyrocko pyrocko' to see if I can reproduce your problem easily, but here Snuffler starts without segfaulting. However, I am running Debian 8 here and not Ubuntu.

Some random remarks:
* on Linux systems, I would recommend to install under the system's native Python as it is usually better maintained and more stable with all its dependencies into system libraries.
* if for some reason you _must_ use Anaconda, install it as a normal user, not with `sudo`. Also, do manual installs under Anaconda as a normal user (only `python setup.py install`, without `sudo`, same for `pip` and `easy_install`, be sure it is using the correct executables under `~/anaconda...`)
* make sure that the correct Python interpreter is called when entering `python` and also when running a tool like `snuffler`, e.g. by running it test-wise with a specific Python interpreter, e.g. `~/anaconda3/bin/python ~/anaconda3/bin/snuffler`
* for problems with dependencies find out what versions of the libraries are actually used with e.g. (example from my test under Anaconda 3 today):
```
$ python -m pyrocko.print_version  deps
pyrocko: pyrocko-2017.11.22-60a9a26220c680b657c12ebe67cd0bf3884e2c26-2017-11-23_10:29:45
numpy: 1.13.3
scipy: 0.19.1
matplotlib: 2.1.0
PyQt: 5.6
Qt: 5.6.2
python: 3.6.
```

Best wishes
Sebastian

**Comment by neatcoder** [comment] 2017-12-18 14:31
Hi!

Thanks for the detailed explanation. I use native Python installation and just wanted to test other installs. Therefore I reported these problems in case somebody else stumbles upon them.

**Comment by HerrMuellerluedenscheid** [comment] 2018-02-01 16:55
I'm closing this issue. Feel free to reopen in case there remain open questions.

**Closed by HerrMuellerluedenscheid** 2018-02-01 16:55 UTC
